name: 'Codesign Xcode App Recursively'
description: 'recursive codesign framework and nested apps inside app bundle'
author: 'tctony'
inputs:
  identity:
    description: 'Cosesign identify, must be installed in keychain before using this action'
    required: true
  path:
    description: 'Path to app to be signed'
    required: true
  options:    
    description: 'optional sign options. such as "--options runtime " for mac app'
    required: false
    default: ''

runs: |
  # 签名嵌套的框架
  find "${{ inputs.path }}" -name "*.framework" -print0 | while read -d $'\0' FRAMEWORK
  do
      codesign --force ${{ inputs.options }} --sign "${{ inputs.identity }}" "$FRAMEWORK"
  done
  # 签名嵌套的应用
  find "${{ inputs.path }}" -name "*.app" -print0 | while read -d $'\0' NESTED_APP
  do
      codesign --force ${{ inputs.options }} --sign "${{ inputs.identity }}" "$NESTED_APP"
  done
  # 签名主应用
  codesign --force ${{ inputs.options }} --sign "${{ inputs.identity }}" "${{ inputs.path }}"
